* Glos E2 verkefni Nannon

** Skipl

** GAmestate


1 2 3 4 5 6 7 8
byrjun
symbolism
W is white triangle
B is black triangle
0 is zero piece
X is X piece
W0 is a white triangle with 0 piece
B0 is a black triangle with 0 piece
WX
BX

- white triangles are on even numbers exept 8
- black on odd except 1



in the beggining
GS = [0,W0,B0,W,B,WX,BX,X]
or
GS = [0,0,0,W,B,X,X,X]


** Experements
1
>>> import nannon
               /\         /\         /\         /\         /\         /\                
  ,.--.,     ,.--.,     ,.--.,      /##\       /  \      ,.--.,     ,.--.,     ,.--.,   
 (  0   )   (  0   )   (  0   )    /####\     /    \    (  X   )   (  X   )   (  X   )  
 | `  ` |   | `  ` |   | `  ` |   /######\   /      \   | `  ` |   | `  ` |   | `  ` | 
  ` ^^ `   / ` ^^ ` \ / ` ^^ ` \ /########\ /        \ / ` ^^ ` \ / ` ^^ ` \   ` ^^ `   
>>> bla = nannon.moveLegal(nannon.GS,3,3,'PO')
>>> bla
True
>>> 

// Thetta ma kalla sucessfull test a moveLegal fallinu.. 
2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nannon
               /\         /\         /\         /\         /\         /\                
  ,.--.,     ,.--.,     ,.--.,      /##\       /  \      ,.--.,     ,.--.,     ,.--.,   
 (  0   )   (  0   )   (  0   )    /####\     /    \    (  X   )   (  X   )   (  X   )  
 | `  ` |   | `  ` |   | `  ` |   /######\   /      \   | `  ` |   | `  ` |   | `  ` | 
  ` ^^ `   / ` ^^ ` \ / ` ^^ ` \ /########\ /        \ / ` ^^ ` \ / ` ^^ ` \   ` ^^ `   
>>> nxt1 = nannon.Move(nannon.GS,3,3,'PO')
               /\         /\         /\         /\         /\         /\                
             ,.--.,     ,.--.,      /##\       /  \      ,.--.,     ,.--.,     ,.--.,   
            (  0   )   (  0   )    /####\     /    \    (  X   )   (  X   )   (  X   )  
            | `  ` |   | `  ` |   /######\   /      \   | `  ` |   | `  ` |   | `  ` | 
           / ` ^^ ` \ / ` ^^ ` \ /########\ /        \ / ` ^^ ` \ / ` ^^ ` \   ` ^^ `   
>>> 

// Ekki alv succsess Move pr'ofun

3

Python 2.6.6 (r266:84292, Dec 27 2010, 00:02:40) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nannon
               /\         /\         /\         /\         /\         /\                
  ,.--.,     ,.--.,     ,.--.,      /##\       /  \      ,.--.,     ,.--.,     ,.--.,   
 (  0   )   (  0   )   (  0   )    /####\     /    \    (  X   )   (  X   )   (  X   )  
 | `  ` |   | `  ` |   | `  ` |   /######\   /      \   | `  ` |   | `  ` |   | `  ` | 
  ` ^^ `   / ` ^^ ` \ / ` ^^ ` \ /########\ /        \ / ` ^^ ` \ / ` ^^ ` \   ` ^^ `   
>>> nxt1 = nannon.Move(nannon.GS,3,3,'PO')
               /\         /\         /\         /\         /\         /\                
             ,.--.,     ,.--.,     ,.--.,      /  \      ,.--.,     ,.--.,     ,.--.,   
            (  0   )   (  0   )   (  0   )    /    \    (  X   )   (  X   )   (  X   )  
            | `  ` |   | `  ` |   | `  ` |   /      \   | `  ` |   | `  ` |   | `  ` | 
           / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \ /        \ / ` ^^ ` \ / ` ^^ ` \   ` ^^ `   
>>> nxt1 = nannon.Move(nxt1,2,4,'PX')
               /\         /\         /\         /\         /\         /\                
             ,.--.,     ,.--.,     ,.--.,     ,.--.,     ,.--.,      /  \      ,.--.,   
            (  0   )   (  0   )   (  0   )   (  X   )   (  X   )    /    \    (  X   )  
            | `  ` |   | `  ` |   | `  ` |   | `  ` |   | `  ` |   /      \   | `  ` | 
           / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \ /        \   ` ^^ `   
>>> nxt1 = nannon.Move(nxt1,1,6,'PX')
               /\         /\         /\         /\         /\         /\                
             ,.--.,     ,.--.,     ,.--.,     ,.--.,     ,.--.,     ,.--.,              
            (  0   )   (  0   )   (  0   )   (  X   )   (  X   )   (  X   )             
            | `  ` |   | `  ` |   | `  ` |   | `  ` |   | `  ` |   | `  ` | 
           / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \            
>>> nxt1 = nannon.Move(nxt1,5,7,'PO')
               /\         /\         /\         /\         /\         /\                
             ,.--.,      /  \      ,.--.,     ,.--.,     ,.--.,     ,.--.,              
            (  0   )    /    \    (  0   )   (  X   )   (  X   )   (  X   )             
            | `  ` |   /      \   | `  ` |   | `  ` |   | `  ` |   | `  ` | 
           / ` ^^ ` \ /        \ / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \ / ` ^^ ` \            
>>> 
                             

// Frekar successfull daemi.. 


4. 

new nannon.py, seems to work...




5.  abati2.py er málið, held ég endanl útgáfa af forritinu.
** ASCI list fyrir leikinn

|
 \|_|


  /__/
 |   |
 | o |
 |___|


** Testing


kerfid:

Notendur -> kerfid er svartur kassi
Profarar -> grar kassi
Forritarar -> hvitur kassi


*** Test daemi

1

import unittest
import maxutil

class testMaxFunctions(unittest.TestCase):
    def test_maxseq(self):
        self.assertEqual(maxutil.maxseq('abc'),1)
	self.assertEqual(maxutil.maxseq('aaxxxt'), 3)

    def test_maxdiff(self):
        self.assertEqual(maxutil.maxdiff([5,23,1,0]), 22)
	self.assertEqual(maxutil.maxdiff([23,5,1,0]), 18)

if __name__ == '__main__':
    unittest.main(verbosity=2, exit=False)

*** Profhogun

aeskilegt hlutfall profkoda/kerfiskoda  2:1 eda 3:1

keyra oll prof m. einni skipun



GRafik --> 'Virkni Prof' -> Notendur

*** Gallar




i farid ur jadar olli ad, skifu stafli hvarf
-> orsok Empty board lausn tok ekki tillit til Home stafna
     -> vidgerd svoldid hakk, hvert tilfelli tekid fyrir sig 
         i if yrdingum inni Move falli..:P

ii ljeleg villumedhondlun upprunalega i getNextMove, int() tholdi ekki non digit
  input -> olli krashi vid raungu inputi, skemmir leik

  -> lausn .isdigit() tjekkk, + tjekk hvort digitid er i rjetta range


iii getNextMove roll vessen, var lengi ad fatta ad roll var thar tekid sem
    int en ekki fallid roll(), ef roll parameterinn var notadur

    -> breyti i roll1


iV getLegalMoves hack,  tharf ad breyta rolli thannig ad move legal virki
   rjett, svoldid hakk lausn, en getLegalMoves og moveLegal, vinna eiginlega
   saman en eru kannski ekki eins sjalfstaed og thau aettu ad vera..


drawboard
adjecents
isWon
playAgain
roll
doStartRoll

og jafnvel Move

Eru allt frekar god foll, einfold allavega.

Hin eru sum, kannski pinu hakk a koflum en virka, samt 
held eg frekar orruglega og fullkomlega.
