* Emacs Org mode
Emacs cheat sheet
https://ccrma.stanford.edu/guides/package/emacs/emacs.html  
** Orgmode with version control
http://orgmode.org/worg/org-tutorials/org-vcs.html
** Hack Emacs
http://www.youtube.com/watch?v=VTh_Xgt69-E

*** markup

*BOLD*, /italic/ _underlined_

*** Links
-http://emacswiki.org

C^cC^o opens link.

: [[http://google.com][Google]]
uncommented below 
 [[http://google.com][Google]]

*** Symbols

LaTeX Symbols

\alpha, \beta, \Beta.

most of these will work.
file links, absolute or relative
- file:/home/bergurth/Desktop/Haust2012/Grep.org
this is an absolute path, otherwise a relative path
is used relative to the current directory
- file:Grep.org
SkipulagsPlaggid
- file:SkipulagsPlag.org

These offer programing capabilities.
Awsome link types
: - elisp:
: - shell:

first activates a peice of elisp code
the second shell code
-These kinds of powerful links give you the ability to 
write Org Mode files that are programs that have "Buttons"
that invoke code.


**** Examples
[[elisp:(color-theme-subtle-hacker)]]
: [[elisp:(color-theme-subtle-hacker)]]
[[elisp:(color-theme-comidia)][Comidia]]

these color themes are missing, need to find out where to get
them.....

: [[shell:ls -lR]]

 [[shell:ls -lR]]
This previous one executes a long ls in the shells current directory

pearl scripts .. also

you can also find a specific line in file

: [[file:bla - Org.org::13][name]
here is line number, one can also search for similar syntax..
: [[file:bla - Org.org::Org Remember][similar syntax]

** :TODO baisics
http://orgmode.org/manual/TODO-Items.html
:todo baisics
http://orgmode.org/manual/TODO-basics.html#TODO-basics

C-c C-t rotates from :todo, done and unmarked

can also be done remotely from timeline and agenda buffers
*** Agenda commands
http://orgmode.org/manual/Agenda-commands.html#Agenda-commands

**** TODO have fun
http://www.linuxjournal.com/article/9116
contains:
 Add the following lines to your ~/.emacs file and restart Emacs:

;; Org-mode settings
(add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-font-lock-mode 1)

this is probably imortant (>.
