* Skipulagsplagg Vor 2012

** Skóli
*** Prófundirbúningur (1)


| NÁMSKEIÐ             | TÍMI                     | STOFA                                       |
|----------------------+--------------------------+---------------------------------------------|
| hugbúnaðarverkefni 1 | Mið. 5. des 9:00-12:00   | A231,HT302,VR-2-V152,155,258,261            |
| hagverkefæði         | Fim. 6. des 9:00-12:00   | A230,A231,VR-2-V138,147,152,155,156,258,261 |
| tölvunet & öryggi    | Fös. 7. des 13:30-16:30  | A050,051,052,207,218,225,229,230,HT302      |
| verkefnastjórnun     | Fim. 13. des 13:30-16:30 | A229,HT102,105                              |
| foritunarmál         | Þri. 18. des 13:30-16:30 | A231,HT302,VR-2-V138,152,155,156,258,261    |
 
ath. hægt að finna út nákv. stofu einhvernveginn á uglu, spyrja Aron.

ath. líka með sjúkrapróf, þ.e.a.s. háttarlag á þeim. [done]

Nú Fimtd. 22. eru 13 daga í fyrsta próf..
og svo 5 í Verkefnastjórnun ..
og svo 4 í Forritunarmál..


13 dagar fyrir, hagverkefæði, Hugbv1, og Tölvunet og örryggi

-> pæling að veikjast 6, og þá verður bara HugbV1
Tölvunet&Öryggi
-> endurtökupr, í mæ




*** Forritunarmál Conceptual skilnings áfangar  (1) 
file:for/ConceptsGlos.org


*** HUG - GPS pælingar  (2)
file:hug/GPSGlos.org
 

*** [done] Prepare new wireless network protocols presentation (1) -skil 3/11/12
it is now the 25th which leaves, 9 days preperation for presentation, 
the actual writing should begin no later than the 29th leaving 5 days 
of easygoing reading and preperation until then.
file:tno/WirlesNetwProtocols.org

finished -> still need to put in references and turn in to teacher



*** [done] Verkefnastjverkefni  (1)                                -skil 29/10/12
file:ver/Verkefni3/GlsV3.org

*** [over] Forritunarmal-v9     (1-3)                              -skil 29/10/12



** Projects
NandtoTetris 3 project  (3)
perfect Mobius mimp project (4)
improve student home page (4)
*** Digital Security pælingar (4)
stenography, key in photo or picture, enigma machine..
læra JavaScript og mögulega CoffeScript (4)
** Other
 Láta Pabbs vita af Óperub mögl. 8 des. Vivaldi.. 
 Látta Pabbs vita af ÓperuBíó-möguleika klk-8 á laugardaginn (3) [done]
 Banki redda námsláni (1)     [done]
 Skattkort í skolann, redda launum (1) [done]
 redda launum frá Nordica + redda vinnu (2)



** Priorities

|               | do soon | do later |
|---------------+---------+----------|
| Important     | 1       | 2        |
| Not Important | 3       | 4        |




** misiatridi

Dropbox -> hi mail + salsa4
