* Alloy 



** Template

module nafn
-- skjolun
open nafn
.
.
.
sig nafn ... {skilgr svida}
.
.
.
lykilord nafn ... {skilgreining}
.
.
.

Reyndar ma sleppa module-linunni og&eda open-linunum og
sig-skilgreiningar mega koma inn a milli klausa.

open svarar til import i java

//
/*

*/

og 
--

 er allt mogul comment adferdir

** General Meaning of stuff

lone: means there is 0 or 1

** MIT tuttorial
http://alloy.mit.edu/alloy4/tutorial4/

http://alloy.mit.edu/alloy4/tutorial4/frame-FS-1.html

*** file system 1

// A file system object
sig FSObject { parent: lone Dir }

// A directory in the file system.
sig Dir extends FSObject { contents: set FSObject }

// A file in the file system.
sig File extends FSObject { }

// A directory is the parent of its contents.
fact { all d: Dir, o: d.contents | o.parent = d }

// All file system objects are either file or directories.
fact { File + Dir = FSObject }

// There exists a root.
one sig Root extends Dir { } { no parent }

// File system is connected.
fact { FSObject in Root.*cintents }

// The contents path is acyclic
assert acyclic { no d: Dir | d in d.^contents }

//File system has one root.
assert oneRoot { one d: Dir | no d.parent }

// Every fd object is in at most one directory
assert oneLocation { all o: FSObject | lone d: Dir | o in d.contents }
