* Gagnaver á Íslandi
-Græn Gagnaver í grend við Grænland
-hópmeðlimir


** Útskýring
útskýra gagnaver


*** -> tegundin sem við ákváðum að fókusa á
    co-location ?
       <) ->  deadicated servers. -> tileinkaðir þjónar.
    má bíða til seinni -> útfærslu lið
   
** Vandamál sem þarf að leysa

kostir og gallar ræddir í s.mb. við neðangreinda liði
*** orkunotkun
    kæling
    rafmagn
**** okkar utfrsla
3.2 Mw í heildinna m. kælingum
2 Mw rafmagn í tæki
*** Tenging við umheiminn.
**** Cantat-3
2.5Gb/s
**** Danice
4x128X10Gb/s
=5,12Tb/s
**** Farice
2X36X10Gb/s
=720Gb/s
**** GreenLand Connect
2X96X10Gb/s
=1,92Tb,s

**** Hugsl seinnipart 2013 Emerald Express
4x100X100Gb/s
=40Tb/s

**** Russian Optical Trans Arctic Cable System ROTACS

*** Starfsfólk

*** Aðgengi að gagnaverinu


** Okkar Uppsetning, möguleg fjárfesting, og fýsileiki/arðsemi
-einn hugsnl útfærslu mögleiki skoðaður-með mögulegri atburðarás

kynning á stofnkostn o.s.f.v.
-áætlaður rekstrareikningur
-áætlað sjóðstreymi.


** stuff eftir

-Verðmat
  núvirða sjóðstreymi.
  ávöxtunarkrafa
*** -heimildaskrá

**** -B.A. ritgerð
Unnur Sigurðardóttir 2011, Gagnaver samkeppnishæfni Íslands, sótt 29 október 2012 af vefslóðinni: 
http://www.google.is/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&ved=0CBwQFjAA&url=http%3A%2F%2Fskemman.is%2Fstream%2Fget%2F1946%2F9758%2F24642%2F1%2FBS_Unnur_Sigur%25C3%25B0ard%25C3%25B3ttir_Gagnaver.pdf&ei=UECcUNa5OOim4gSVzYDQAg&usg=AFQjCNFqHXDMibUlOmQ5JB9g79Yc2_6SOQ

**** -P.W.C. skýrsla   
-->  Benchmarking Study on Iceland as a Location for data center Activity
MAY 2007 Invest in Iceland agency

Contacts
PricewaterhouseCoopers Enterprise Advisory
Woluwe Garden
Woluwedal 18
B-1932 Sint-Stevens-Woluwe
Belgium
Key contact
Jan Desmaretz
Tel     +32 (0)3 259 3390
jan.desmaretz@be.pwc.com


Benchmarking Study on Iceland as a Location for Data Centre Activity. Strenghts. Maí 2007.
PricewaterhouseCoopers – Invest in Iceland Agency. Sótt 3.nóvember 2012 af vefslóðinni:
http://www.invest.is/resources/files/invest.is/BDC%20Report.pdf


**** -Securitas

**** -Del síða
Uppleysingar um verð á tölvubúnaði, Sótt 5. nóvember 2012 af vefslóðinni:
http://www.dell.com/
**** -Advania
http://www.advania.is/um-advania/

-Green Cloud

**** markaðsetning
Uppýsingar um viðmið varðandi netmarkaðsetningu, sótt 8. nóvember 2012 af vefslóðinni:
http://www.avalancheinternetmarketing.com/determine-internet-marketing-budget/


**** Fyrlestur
*** random paels
lan 1.67 milj.

1,67*10^9 kr.


eignir = owners equity
http://is.wikipedia.org/wiki/Eigi%C3%B0_f%C3%A9
eignir = skuldir + eigið fé
eigið fé = eignir - skuldir
