* new Wireless Network protocols

** misc stuff

*** Redda leyser bendi fyrir kynningu

** Old Glos
*** from WLAN.org
 WLAN standardar..
http://compnetworking.about.com/cs/wireless80211/a/aa80211standard.htm

http://en.wikipedia.org/wiki/IEEE_802.11

*** from CNglos.org
 Computer Networks

Wireless LAN  11-hundreds of Mbps
Wired LAN (ethernet) 100 Mbps - 10 Gbps

the gateways are on the network level, the network layer

paeling fra Torfa -->  Port Scanner

www info

wwww.w3.org

**** Vocab for research
Virtual Lan VLAN
VPN's  Virtual Private Networks


** cHAPTR 4

Request To Send (RTS)

Clear To Send (CTS)





** Google search 
https://www.google.com/search?client=ubuntu&channel=fs&q=new+wireless+network+protocols&ie=utf-8&oe=utf-8


** Wireless80211
http://compnetworking.about.com/cs/wireless80211/a/aa80211standard.htm

*** 802.11g
In 2002 and 2003, WLAN products supporting a newer standard called 802.11g emerged on the market.
 802.11g attempts to combine the best of both 802.11a and 802.11b. 802.11g supports bandwidth up 
to 54 Mbps, and it uses the 2.4 Ghz frequency for greater range. 802.11g is backwards compatible 
with 802.11b, meaning that 802.11g access points will work with 802.11b wireless network adapters 
and vice versa.

    Pros of 802.11g - fast maximum speed; signal range is good and not easily obstructed
    Cons of 802.11g - costs more than 802.11b; appliances may interfere on the unregulated signal 
frequency 

*** 802.11n
The newest IEEE standard in the Wi-Fi category is 802.11n. It was designed to improve on 802.11g 
in the amount of bandwidth supported by utilizing multiple wireless signals and antennas (called 
MIMO technology) instead of one.

When this standard is finalized, 802.11n connections should support data rates of over 100 Mbps.
802.11n also offers somewhat better range over earlier Wi-Fi standards due to its increased signal
intensity. 802.11n equipment will be backward compatible with 802.11g gear.

    Pros of 802.11n - fastest maximum speed and best signal range; more resistant to signal 
interference from outside sources
    Cons of 802.11n - standard is not yet finalized; costs more than 802.11g; the use of multiple 
signals may greatly interfere with nearby 802.11b/g based networks. 

additional information about 802.11n
http://en.wikipedia.org/wiki/IEEE_802.11n-2009



*** Baisic on WIFI
from
http://computer.howstuffworks.com/wireless-network1.htm

Uses radios, on router and computer..

transmit on frequencies of 2.4 -5 GHz, higher than  frequencies for cellphones.
Higher frequenciy allows signal to carry more data.


9978:802.11 combines CSMA and MACAW to produce CSMA/CA.
9979-Ethernet is the dominant form of local area networking. It uses CSMA/CD for channel
9980-allocation. Older versions used a cable that snaked from machine to machine, but now twisted
9981-pairs to hubs and switches are most common. Speeds have risen from 10 Mbps to 1 Gbps and
9982-are still rising.

**** Carrier sense multiple access (CSMA)

http://en.wikipedia.org/wiki/Carrier_sense_multiple_access



[Til samanburðar mældist nethraðinn gegnum, WIFI á hávallagötu
16.81 Mbs]


**** 802.11a 
transmits at 5 GHz, and can move upp to 54 megabits a sec
uses
orthagonal frequency-division multiplexing (OFDM) ..

**** 802.11b
transmits at 2.4 GHz 
http://electronics.howstuffworks.com/radio-spectrum.htm
11 megabits per sec
uses complimentary code keying (CCK)..

**** 802.11g 
also transmits at 2.4 GHz but is faster than b.
-can handle up to 54 megabits per second
-because it uses same (OFDM) coding as a.

**** 802.11n
is the newest standard tht is wideley available
http://ieeexplore.ieee.org/search/searchresult.jsp?newsearch=true&queryText=802.11n&x=0&y=0

this standar signifigantly improves speed and range.

g in realworld has performance around 24 Mbs
n can reportedly acheive speeds up to 140 megabits per a second

**** 802.16

líkt og 4G nota OFDM og MIMO, margt lítur út fyrir að
4G og WIMAx þ.e.a.s. 802.16 eru að stefna samann

**** more general stuff

many wireless adapters can use more than one 802.11 standard


**** Wireleaa security

***** WEP

uses TKIP encryption

***** WPA 

***** media access Control  (MAC) address 
(MAC) address filtering

it is possible to spoof a mac address


** Grep Research quotes

L3280

The location of the ISM bands varies somewhat from country to country. In the United States, for example,
devices whose power is under 1 watt can use the bands shown in Fig. 2-13 without requiring a FCC license. The
900-MHz band works best, but it is crowded and not available worldwide. The 2.4-GHz band is available in most
countries, but it is subject to interference from microwave ovens and radar installations. Bluetooth and some of
the 802.11 wireless LANs operate in this band. The 5.7-GHz band is new and relatively undeveloped, so
equipment for it is expensive, but since 802.11a uses it, it will quickly become more popular.
Figure 2-13. The ISM bands in the United States.

*** Wep origins
1.5.4 Wireless LANs: 802.11
Almost as soon as notebook computers appeared, many people had a dream of walking into an office and
magically having their notebook computer be connected to the Internet. Consequently, various groups began
working on ways to accomplish this goal. The most practical approach is to equip both the office and the
notebook computers with short-range radio transmitters and receivers to allow them to communicate. This work
rapidly led to wireless LANs being marketed by a variety of companies.
The trouble was that no two of them were compatible. This proliferation of standards meant that a computer
equipped with a brand X radio would not work in a room equipped with a brand Y base station. Finally, the
industry decided that a wireless LAN standard might be a good idea, so the IEEE committee that standardized
the wired LANs was given the task of drawing up a wireless LAN standard. The standard it came up with was
named 802.11. A common slang name for it is WiFi. It is an important standard and deserves respect, so we will
call it by its proper name, 802.11.
The proposed standard had to work in two modes:
1. In the presence of a base station.
2. In the absence of a base station.
In the former case, all communication was to go through the base station, called an access point in 802.11
terminology. In the latter case, the computers would just send to one another directly. This mode is now
sometimes called ad hoc networking. A typical example is two or more people sitting down together in a room
not equipped with a wireless LAN and having their computers just communicate directly. The two modes are
illustrated in Fig. 1-35.
Figure 1-35. (a) Wireless networking with a base station. (b) Ad hoc networking.

*** 802.11 bluetooth Stuff

9263:Because both 802.11 and Bluetooth operate in the 2.4-GHz ISM band on the same 79
9264:channels, they interfere with each other. Since Bluetooth hops far faster than 802.11, it is far
9265:more likely that a Bluetooth device will ruin 802.11 transmissions than the other way around.
9266:Since 802.11 and 802.15 are both IEEE standards, IEEE is looking for a solution to this
9267-problem, but it is not so easy to find since both systems use the ISM band for the same
9268:reason: no license is required there. The 802.11a standard uses the other (5 GHz) ISM band,



*** Security and bridging

9469:Another point is security. Both 802.11 and 802.16 support encryption in the data link layer.
9470-Ethernet does not. This means that the various encryption services available to the wireless
9471-networks are lost when traffic passes over an Ethernet. Worse yet, if a wireless station uses
9472-data link layer encryption, there will be no way to decrypt it when it arrives over an Ethernet.
9473-If the wireless station does not use encryption, its traffic will be exposed over the air link.
9474-Either way there is a problem.
9475:One solution to the security problem is to do encryption in a higher layer, but then the 802.11
9476:station has to know whether it is talking to another station on an 802.11 network (meaning
9477-use data link layer encryption) or not (meaning do not use it). Forcing the station to make a
9478-choice destroys transparency.



*** around 24356 security WEP

WEP Wired Equivalent Privacy

** Orthagonal Frequency Division Multiplexing OFDM
http://en.wikipedia.org/wiki/Orthogonal_frequency-division_multiplexing#Wireless
is used by:
WLAN:   IEEE 802.11a,g,n and HIPERLAN
