* Verkefnisgreining


** atriði:

*** Auglýsingasöfnun
kaup á auglýsingum
*** Tölvuvinna
Forritun, prófun á innsláttarforriti
*** Leiga á húsnæði
Prentun
*** Samskipti við Grandmastera
Kaup á farseðlum
Bókun á gistiaðstöðu
Leiga á rútu
vinna við komuþóknun
Panta mat fyrir Grandmastera
*** Pöntun Blóma
kaup á borðdúkum

*** Ráðning starfsmanna
*** Vinna við verðlaun
*** Vinna við matarmiða
*** Setning móts
Uppsetning hljóð og myndkerfa
Skákkeppni
Afhending blóma
Verðlaunaafhending
*** Mótslit
frágangur hús
GM ferjaðir í flug

** Útkoma

Útkomurnar eru þær niðurstöður sem lagt er upp með að ná í verkefninu sjálfu.  Útkoma verkefnis sem er 
fyrirfram ákveðinn og undirbúinn er líklegri til að nást fram. Ákjósanlegar og/eða mögulegar niðurstöður
eru settar fram í töflu hér að neðan þar sem þær eru svo greindar m.t.t. verkefnis. Ef við greinum hvar 
þörfin er hvað mest á verkefnastjórnun þá getum við mögulega áttað okkur á mikilvægustu þáttunum í 
verkefninu og þar með stuðlað að því að viðeigandi útkoma náist í verkefninu.  Skýringar eru gefnar á
hverjum verkefnisþátt í texta fyrir neðan töfluna.


| Mögulegar niðurstöður/vńtingar    | Mikilvægi fyrir árangur verkefnis (1-5) | Áhætta á að takist ekki (1-5) | Þörf á verkefnastjórnun(margfeldi) |
|-----------------------------------+-----------------------------------------+-------------------------------+------------------------------------|
| Mót stenst kröfur mótsgesta       |                                       5 |                             2 |                                 20 |
| Húsnæði og aðbúnaður              |                                       5 |                             2 |                                 20 |
| margir GM's mæta                  |                                       4 |                             2 |                                 12 |
| mót stenst kröfur GM's, keppenda  |                                       3 |                             3 |                                 10 |
| hljóð°, mynd og tölvukerfi        |                                       4 |                             4 |                                 14 |
| Auglysingarsölu tekjur            |                                       4 |                             4 |                                 14 |
| margir mætta og fylgjast með      |                                       2 |                             3 |                                 16 |
|                                   |                                         |                               |                                    |
| Framboð á mat og áfengi           |                                       4 |                             4 |                                  8 |
| mót stenst kröfur annara keppenda |                                         |                               |                                    |



 Mikilvægustu þættirnir eru að mótið standist kröfur gesta og að húsnæði og aðbúnaður séu í lagi.
Þetta eru einnig liðir þar sem metið er að sé mikil þörf á verkefnastjórnun.  Hægt er að innleiða 
ýmsa gæðastjórnunarferla í því skyni að minka áhættuna hér.  Í fylgjandi texta er fjallað ítarlegar
um hvern lið í töflunni að ofan.

*** Mót stenst kröfur mótsgesta

  Mikilvægt er að skákmótið standist þeirra krafa sem gestir skákmótsins og keppendur gera almennt
til skákmóta, og einkum og sér í lagi til skákmóts reykjavíkur sem hefur skappað sér góðs orðstírs
og hefur ákveðna sögu á bak við sig.
 Til að takmarka áhættuna á því að skákmótið standist ekki kröfur gesta og keppenda er hægt að miða
við reynslu fyrri móta og ganga út frá því sem fyr hefur verið gert og setja sig í sambandi við þá sem
hafa staðið að þessu áður.  Auk þess væri möguleiki að gera skoðannakönnun á meðal markhópsins sem er
talin líklegur til ða mæta á mótið og athuga hvaða kröfur það gerir til skákmótsins.

*** Húsnæði og Aðbúnaður

  Eins og menn vita er veðrið á íslandi frægt fyrir sýn skjótu umskipti, eins og saman ber máltakið 
"Skjót skipast veður í lofti" því ætti að vera öllum ljóst að ekki sé hægt að ættla sér að halda mótið
utandyra. Heldur krefur nauðsyn þess ekki bara að húsnæði sé til staðar heldur þarf það einnig að 
fullnæga kröfum mótsgesta.  Eins er með allan aðbúnaðinn almennt. Hann þarf líka að standast þær kröfur 
sem að skákmótsgestir og keppendur koma til með að gera.  Hin ýmsu skilyrði koma hér við sögu en á meðal
þeira er að húsið þarf að vera nægilega rúmgott til að geta tekið ámóti gestum og keppendum við þær 
aðstæður sem eru í skákmóti, jafnframt því að uppfylla öryggistaðla.  Eins þarf hljóðumhverfið að hafa 
vissa eiginleika, ekki má vera hávaði á svæðinnu eða hljómbærni frá svæðum þar sem kynni að myndast 
mögulega hávaði á tíma mótsins, þ.a. hljóðeinangrun þarf að vera til staðar.  Samgöngur skipta máli þar 
sem gestirnir eru margir utanaðlandskomandi og er því staðsetningar í grend við samgöngumiðstöðvar 
bægjarins heppilegar í þessu skyni.
  
*** Margir GrandMasterar mæta

  Mótið er jafnframt því að vera keppni einnig á margann hátt einskonar ráðstefna þeirra sem hafa 
skákina að áhugamáli.  Meiri samkepni í kepninni sjálfri eflir mótið og skákhreyfinguna hér á íslandi
og víðar.  Eins gera áhugaverðir alþjóðlegir og öflugir skákmenn sitt til að efla áhugann á mótinu og 
jafnframt skerpa og bæta skákmenninguna hér á Íslandi.  Stál brýnir stál eins og menn segja.
  Besta leiðinn til að fá sem mesta hágæða skákmenn til landsins er að átta sig á kröfum þeirra og 
verða að þeim óskum sem skynsamlega sé hægt að uppfylla.  Með því að uppfylla sem mest af kröfum GM's 
er hægt að lágmarka áhættuna á að fáir mæta.

   
*** Mót stenst kröfur Grandmastera

  Mikilvægt er að mótið standist kröfur þeirra meistara sem mæta á það.  Helst upp að því marki að þeir
sjá sig fært eða finna sig knúinn til að mæta, en helst ekki mikkið umfram það.  þ.e.a.s. ekki er 
nauðsynlegt að mótið standis ýtrustu kröfur allra Grandmasteranna, heldur bara að það standist nóugu 
miklum kröfum þ.a. sem flestir mæta. 


*** hljóð, mynd og tölvukerfi


*** Auglýsingasölu tekjur

Að mótið nái að selja auglysingar er gott uppá að lágmarka tapið sem verður á mótinu.  

*** Margir mæta og fylgjast með

 Góð mæting á mótið mun eflaust spila ákveðna rullu í því hvort mótið verði skynjað sem vel heppnað.  Eins
má vænta að góð mæting á gott mót gæti komið til með að efla og útbreiða skákmenninguna á Íslandi, eins 
mun góð reynsla af mótinu hjá erlendum gestum eflaust vera góð landkynning og þar með efla land og þjóð.
 Til þess að mætinginn verði góð þá þarf kynning á mótinu að vera nægileg og þarf sú kynnig að ná að sýna
mótið í jákvæðu ljósi.


*** Framboð á mat og áfengi 

Gott er að hafa ....
